version: '2.0'
services:
 config-service:
    image: config-service
    ports:
        - "8888:8888"
    networks:
        - my-network

 discovery-service:
    image: discovery-service
    ports:
        - "8761:8761"
    depends_on:
        - config-service
    networks:
        - my-network

 product-service:
    image: product-service
    ports:
        - "8080:8080"
    depends_on:
        - config-service
    networks:
        - my-network
proxy-service:
    image: proxy-service
    ports:
        - "8888:8888"
    depends_on:
        - config-service
    networks:
        - my-network
networks:
    my-network:
       driver: bridge